include:
  # Include the templates for php jobs
  - 'https://git.itapps.miamioh.edu/solution-delivery-dev/gitlab-ci-includes/raw/1.0/php/php-job-templates.yaml'
  # Set up the standard Laravel pipeline
  - 'https://git.itapps.miamioh.edu/solution-delivery-dev/gitlab-ci-includes/raw/1.0/php/laravel-pipeline.yaml'
  # Include unit testing, analysis and feature testing jobs
  - 'https://git.itapps.miamioh.edu/solution-delivery-dev/gitlab-ci-includes/raw/1.0/php/php-unit.yaml'
  - 'https://git.itapps.miamioh.edu/solution-delivery-dev/gitlab-ci-includes/raw/1.0/php/php-analysis.yaml'
  - 'https://git.itapps.miamioh.edu/solution-delivery-dev/gitlab-ci-includes/raw/1.0/php/php-feature.yaml'
  # Run the php code quality assessment (coverage and CRAP score)
  - 'https://git.itapps.miamioh.edu/solution-delivery-dev/gitlab-ci-includes/raw/1.0/php/php-quality.yaml'
  # Include jobs to build and deploy the RPM
  - 'https://git.itapps.miamioh.edu/solution-delivery-dev/gitlab-ci-includes/raw/1.0/deploy/rpm.yaml'
  - 'https://git.itapps.miamioh.edu/solution-delivery-dev/gitlab-ci-includes/raw/1.0/deploy/puppet.yaml'
