variables:
  UNIT_TESTS_PATH: tests/Unit
  FEATURE_TESTS_PATH: tests/Feature
  MINIMUM_COVERAGE_PERCENT: 85
  MAXIMUM_CRAP_SCORE: 30

stages:
  - test
  - analyze
  - review

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

before_script:
  - composer install --quiet

unit:
  stage: test
  image: miamioh/php:7.3-phpunit
  except:
    - test
    - production
  script:
    - run $UNIT_TESTS_PATH

coverage:
  stage: analyze
  image: miamioh/php:7.3-phpunit-coverage
  script:
    - run $UNIT_TESTS_PATH
  artifacts:
    paths:
      - coverage
      - clover.xml
    reports:
      junit: coverage/phpunit.junit.xml
    expire_in: 1 week
  except:
    - test
    - production

quality:
  stage: review
  image: miamioh/php:coverage
  script:
    - run -p $MINIMUM_COVERAGE_PERCENT -s $MAXIMUM_CRAP_SCORE
  dependencies:
    - coverage
  except:
    - test
    - production

